# Locking the screen
bind = $mainMod, escape, exec, loginctl lock-session
bind = $mainMod & Shift_L, escape, exec, (sleep 1; systemctl suspend) & loginctl lock-session

# Taking screenshots
bind = , Print, exec, hyprshot --freeze --silent --mode region
bind = Shift_L, Print, exec, hyprshot --freeze --silent --mode window
bind = Ctrl_L&Shift_L, Print, exec, hyprshot --silent --mode output
