# Locking the screen, suspending, logging out, etc
bind = $mainMod, Escape, exec, loginctl lock-session
bind = $mainMod Ctrl, Escape, exec, (sleep 1; systemctl suspend) & loginctl lock-session
bind = $mainMod Ctrl Shift, Escape, exit,

# Taking screenshots
bind = , Print, exec, hyprshot -o ~/Pictures/Screenshots --freeze --silent --mode region
bind = Shift, Print, exec, hyprshot -o ~/Pictures/Screenshots --freeze --silent --mode window
bind = Ctrl Shift, Print, exec, hyprshot -o ~/Pictures/Screenshots --silent --mode output
