# See https://wiki.hypr.land/0.54.0/Configuring/Window-Rules/

# Example windowrule
# windowrule = float, match:class ^(kitty)$, match:title ^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*

# Prevent new mail from bringing hidden terminal running mutt to the front
windowrule = suppress_event activatefocus, match:class ^(kitty)$

# Change border on maximised window to distinguish it from a single tiled window
windowrule = border_color $base, match:fullscreen 1

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0

# Float dialogs
windowrule = float on, match:class xdg-desktop-portal-gtk

## App-specific rules

# btop
windowrule = center on, float on, size (monitor_w*0.8) (monitor_h*0.9), match:title btop

# darktable
windowrule = center on, float on, match:title darktable starting

# Enpass
windowrule = center on, float on, match:class Enpass
windowrule = size (monitor_w*0.5) (monitor_h*0.66), match:class Enpass, match:title Enpass
windowrule = move (cursor_x-(window_w*0.5)) (cursor_y-(window_h*0.5)), match:title Enpass Assistant

# Firefox
windowrule = float on, persistent_size on, match:class firefox, match:title Picture-in-Picture
windowrule = float on, persistent_size on, match:class firefox, match:title Library

# GNOME Pomodoro
windowrule = pseudo on, size (monitor_w*0.25) (monitor_h*0.55), match:class gnome-pomodoro, match:title Pomodoro
windowrule = workspace special:scratch, match:class gnome-pomodoro
windowrule = float on, persistent_size on, match:class gnome-pomodoro, match:title Preferences

# nwg-look
windowrule = center on, float on, match:class nwg-look
windowrule = size (monitor_w*0.33) (monitor_h*0.5), match:class nwg-look, match:title nwg-look

# Obsidian
windowrule = size (monitor_w*0.45) (monitor_h*0.9), pseudo on, workspace special:notes, match:class obsidian

# Messaging apps
windowrule = size (monitor_w*0.45) (monitor_h*0.7), pseudo on, workspace special:comms, match:class ^(discord)
windowrule = size (monitor_w*0.45) (monitor_h*0.7), pseudo on, workspace special:comms, match:class ^(com.fastmail.Fastmail)
windowrule = size (monitor_w*0.45) (monitor_h*0.7), pseudo on, workspace special:comms, match:class ^(com.slack.Slack)
windowrule = size (monitor_w*0.45) (monitor_h*0.7), pseudo on, workspace special:comms, match:class ^(org.signal.Signal)
